In [1]:
import tensorflow as tf
tf.__version__
from tensorflow.python.client import device_lib
device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 8133552907824534086,
 name: "/device:XLA_CPU:0"
 device_type: "XLA_CPU"
 memory_limit: 17179869184
 locality {
 }
 incarnation: 15581516555459346216
 physical_device_desc: "device: XLA_CPU device",
 name: "/device:GPU:0"
 device_type: "GPU"
 memory_limit: 6918604064
 locality {
   bus_id: 1
   links {
   }
 }
 incarnation: 15040998855063717675
 physical_device_desc: "device: 0, name: NVIDIA GeForce RTX 2080 SUPER, pci bus id: 0000:01:00.0, compute capability: 7.5",
 name: "/device:XLA_GPU:0"
 device_type: "XLA_GPU"
 memory_limit: 17179869184
 locality {
 }
 incarnation: 8199571755367449316
 physical_device_desc: "device: XLA_GPU device"]

In [2]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

In [3]:
tf.debugging.set_log_device_placement(True)

a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
c = tf.matmul(a, b)
print(c)

Executing op MatMul in device /job:localhost/replica:0/task:0/device:GPU:0
tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)


In [4]:
import keras
from keras.models import Sequential, Model
from keras import layers, applications, optimizers
from keras.layers import Conv2D, MaxPooling2D, Dropout, Flatten, Dense, Activation,GlobalMaxPooling2D
from keras.preprocessing.image import ImageDataGenerator, load_img

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2
import random

In [5]:
epoch = 100
batch_size = 5
image_size = 224

In [6]:
#load train data(25000 imgs each)

filenames = os.listdir('./input/train/train')
data = []
categories = []

for filename in filenames:
    category = filename.split('.')[0]
    if category == 'dog':
        categories.append(1)
    else:
        categories.append(0)
    
    image = keras.preprocessing.image.load_img(os.path.join('./input/train/train', filename),
                                               color_mode='rgb',
                                               target_size= (image_size,image_size))
    image = np.array(image)
    data.append(image)

data = np.array(data)
categories = np.array(categories)

print(data)
print(categories)

[[[[203 164  87]
   [206 167  90]
   [209 170  93]
   ...
   [245 203 119]
   [241 202 123]
   [239 200 121]]

  [[203 164  87]
   [206 167  90]
   [209 170  93]
   ...
   [245 205 120]
   [242 203 124]
   [240 201 122]]

  [[203 164  87]
   [206 167  90]
   [209 170  93]
   ...
   [245 204 122]
   [243 204 125]
   [241 202 123]]

  ...

  [[154 123  56]
   [155 124  57]
   [156 125  58]
   ...
   [  3   3   1]
   [  3   3   1]
   [  3   3   1]]

  [[153 122  55]
   [153 122  55]
   [154 123  56]
   ...
   [  2   2   0]
   [  2   2   0]
   [  2   2   0]]

  [[151 120  53]
   [152 121  54]
   [153 122  55]
   ...
   [  1   1   0]
   [  1   1   0]
   [  1   1   0]]]


 [[[ 39  44  40]
   [ 40  44  43]
   [ 41  45  46]
   ...
   [210 209 181]
   [207 204 171]
   [201 199 161]]

  [[ 40  45  41]
   [ 40  44  43]
   [ 41  45  46]
   ...
   [207 203 176]
   [203 200 169]
   [197 195 157]]

  [[ 39  44  40]
   [ 38  42  41]
   [ 37  41  42]
   ...
   [195 191 166]
   [198 193 164]
   [205 200

In [7]:
# shuffle dataset

idx = np.random.permutation(len(data))
data, categories = data[idx], categories[idx]

In [9]:
# split train 6(15,000) / val 2(5,000) / test 2(5,000)

x_train = data[:15000]
y_train = categories[:15000]
x_temp, y_temp = data[-10000:], categories[-10000:]

from sklearn.model_selection import train_test_split

x_val, x_test, y_val, y_test = train_test_split(x_temp, y_temp, test_size=0.5)

In [10]:
print(x_train, y_train)

print(x_temp, y_temp)
print(x_temp.shape, y_temp.shape)

print(x_val, y_val)

print(x_test, y_test)
print(x_test.shape, y_test.shape)

[[[[192 191 197]
   [210 209 215]
   [185 184 190]
   ...
   [195 192 199]
   [198 195 202]
   [179 178 186]]

  [[199 198 204]
   [205 204 210]
   [194 193 199]
   ...
   [195 192 199]
   [181 178 185]
   [182 181 189]]

  [[197 196 202]
   [196 195 201]
   [193 192 198]
   ...
   [197 194 201]
   [179 176 183]
   [195 194 202]]

  ...

  [[253 253 253]
   [248 248 248]
   [251 251 251]
   ...
   [248 246 247]
   [244 242 243]
   [245 245 245]]

  [[251 251 251]
   [248 248 248]
   [251 251 251]
   ...
   [247 245 246]
   [245 243 244]
   [242 242 242]]

  [[247 247 247]
   [250 250 250]
   [250 250 250]
   ...
   [240 238 239]
   [243 241 242]
   [248 248 248]]]


 [[[141 146 140]
   [142 147 141]
   [144 149 143]
   ...
   [186 192 182]
   [188 194 184]
   [180 186 176]]

  [[142 147 141]
   [143 148 142]
   [144 149 143]
   ...
   [179 185 175]
   [174 180 170]
   [175 181 171]]

  [[142 147 141]
   [143 148 142]
   [145 150 144]
   ...
   [180 186 176]
   [186 192 182]
   [180 186

In [11]:
def build_vgg_block(input_layer, num_cnn=3, channel=64, block_num=1):
    x = input_layer
    
    for cnn_num in range(num_cnn):
        x = keras.layers.Conv2D(
            filters=channel,
            kernel_size=(3,3),
            activation='relu',
            kernel_initializer='he_normal',
            padding='same',
            name=f'block{block_num}_conv{cnn_num}')(x)

    x = keras.layers.MaxPooling2D(
        pool_size=(2, 2),
        strides=2,
        name=f'block{block_num}_pooling')(x)

    return x

In [12]:
def build_vgg(input_shape=(image_size,image_size,3),
              num_cnn_list=[2,2,3,3,3],
              channel_list=[64,128,256,512,512],
              num_classes=2):
    input_layer = keras.layers.Input(shape=input_shape)
    output = input_layer
    
    for i, (num_cnn, channel) in enumerate(zip(num_cnn_list, channel_list)):
        output = build_vgg_block(
            output,
            num_cnn=num_cnn, 
            channel=channel,
            block_num=i
    )
        
    output = keras.layers.Flatten(name='flatten')(output)
    output = keras.layers.Dense(4096, activation='relu', kernel_regularizer='l2', name='fc1')(output)
    output = keras.layers.Dropout(0.5)(output)
    output = keras.layers.Dense(4096, activation='relu', kernel_regularizer='l2', name='fc2')(output)
    output = keras.layers.Dropout(0.5)(output)
    output = keras.layers.Dense(num_classes, activation='softmax', name='predictions')(output)
    
    model = keras.Model(
        inputs=input_layer, 
        outputs=output
    )
    return model

In [13]:
%load_ext tensorboard

import datetime

In [14]:
model = build_vgg()

Executing op TruncatedNormal in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Mul in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Add in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Assert in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Fill in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Assert in device /job:localhost/re

Executing op Assert in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Fill in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Assert in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op TruncatedNormal in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Mul in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Add in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarIsInitializedOp in device /job:localh

Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Assert in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op RandomUniform in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Sub in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Mul in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Add in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Assert in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AssignVariableOp in device /job:localhost/

In [15]:
model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer=tf.keras.optimizers.SGD(learning_rate=0.01, momentum=0.9, clipnorm=1.),
    metrics=['accuracy']
)

Executing op Fill in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Assert in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Fill in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Assert in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarHandleOp in device /job:lo

In [16]:
model.summary()

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
block0_conv0 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block0_conv1 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block0_pooling (MaxPooling2D (None, 112, 112, 64)      0         
_________________________________________________________________
block1_conv0 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block1_pooling (MaxPooling2D (None, 56, 56, 128)      

In [17]:
log_dir = "logs/vgg_minibatch/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

In [18]:
from keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau

early_stopping = EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=10)
model_checkpoint = ModelCheckpoint('vgg16.h5', monitor='val_loss', mode='min', verbose=1, save_best_only=True)

In [19]:
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.1, patience=5, min_lr=0.00001)

In [ ]:
# without early stopping

epoch = 50

history = model.fit(
    x_train, y_train,
    epochs=epoch,
    validation_data=(x_val, y_val),
    validation_steps=x_val.size//batch_size,
    steps_per_epoch=x_test.size//batch_size,
    verbose=1,
    #callbacks=[tensorboard_callback, early_stopping, model_checkpoint]
    callbacks=[tensorboard_callback, reduce_lr]
)

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op RangeDataset in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op RepeatDataset in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op MapDataset in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op PrefetchDataset in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op FlatMapDataset in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op TensorDataset in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op RepeatDataset in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ZipDataset in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ParallelMapDatasetV2 in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Add in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op SummaryWriter 

Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Assert in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Fill in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Assert in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Fill in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarIsInitializedOp in device 

Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Assert in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Fill in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Assert in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Fill in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op LogicalNot in device /job:loc

       24/150528000 [..............................] - ETA: 2083:26:48 - loss: 280.6432 - accuracy: 0.5833Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
       26/150528000 [..............................] - ETA: 2083:36:59 - loss: 267.3820 - accuracy: 0.6154Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
       28/150528000 [..............................] - ETA: 2083:40:52 - loss: 257.6363 - accuracy: 0.6071Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
       31/150528000 [..............................] - ETA: 2083:51:34 - loss: 245

       75/150528000 [..............................] - ETA: 2087:37:20 - loss: 182.0719 - accuracy: 0.6000Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
       78/150528000 [..............................] - ETA: 2088:01:46 - loss: 179.0006 - accuracy: 0.5897Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
       80/150528000 [..............................] - ETA: 2087:54:02 - loss: 177.0232 - accuracy: 0.6000Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
       85/150528000 [..............................] - ETA: 2089:39:20 - loss: 172

      121/150528000 [..............................] - ETA: 2089:51:23 - loss: 151.6428 - accuracy: 0.5289Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      123/150528000 [..............................] - ETA: 2089:46:30 - loss: 150.7454 - accuracy: 0.5203Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      126/150528000 [..............................] - ETA: 2089:42:18 - loss: 149.4516 - accuracy: 0.5159Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      128/150528000 [..............................] - ETA: 2089:20:12 - loss: 148

      171/150528000 [..............................] - ETA: 2090:32:50 - loss: 135.8355 - accuracy: 0.4795Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      173/150528000 [..............................] - ETA: 2090:14:37 - loss: 135.3596 - accuracy: 0.4798Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      175/150528000 [..............................] - ETA: 2089:57:11 - loss: 134.8928 - accuracy: 0.4800Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      178/150528000 [..............................] - ETA: 2089:57:36 - loss: 134

      219/150528000 [..............................] - ETA: 2089:39:07 - loss: 126.7553 - accuracy: 0.4612Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      221/150528000 [..............................] - ETA: 2089:30:43 - loss: 126.4360 - accuracy: 0.4615Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      229/150528000 [..............................] - ETA: 2090:37:56 - loss: 125.1987 - accuracy: 0.4629Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      231/150528000 [..............................] - ETA: 2090:24:13 - loss: 124

      267/150528000 [..............................] - ETA: 2098:37:09 - loss: 119.8632 - accuracy: 0.4682Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      269/150528000 [..............................] - ETA: 2098:21:48 - loss: 119.6023 - accuracy: 0.4684Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      271/150528000 [..............................] - ETA: 2098:06:42 - loss: 119.3444 - accuracy: 0.4649Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      273/150528000 [..............................] - ETA: 2097:52:03 - loss: 119

      313/150528000 [..............................] - ETA: 2095:11:28 - loss: 114.2093 - accuracy: 0.4728Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      316/150528000 [..............................] - ETA: 2095:03:12 - loss: 113.8542 - accuracy: 0.4747Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      318/150528000 [..............................] - ETA: 2094:59:11 - loss: 113.6160 - accuracy: 0.4780Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      320/150528000 [..............................] - ETA: 2094:48:42 - loss: 113

      363/150528000 [..............................] - ETA: 2093:23:53 - loss: 108.4339 - accuracy: 0.4848Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      365/150528000 [..............................] - ETA: 2093:14:17 - loss: 108.2092 - accuracy: 0.4849Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      367/150528000 [..............................] - ETA: 2093:09:51 - loss: 107.9809 - accuracy: 0.4877Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      369/150528000 [..............................] - ETA: 2093:07:13 - loss: 107

      416/150528000 [..............................] - ETA: 2090:45:00 - loss: 102.5963 - accuracy: 0.4928Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      418/150528000 [..............................] - ETA: 2090:37:35 - loss: 102.3812 - accuracy: 0.4928Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      420/150528000 [..............................] - ETA: 2090:35:48 - loss: 102.1697 - accuracy: 0.4929Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      422/150528000 [..............................] - ETA: 2090:28:19 - loss: 101

      468/150528000 [..............................] - ETA: 2089:00:10 - loss: 97.2144 - accuracy: 0.4893Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      470/150528000 [..............................] - ETA: 2089:03:22 - loss: 97.0150 - accuracy: 0.4894Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      472/150528000 [..............................] - ETA: 2088:57:34 - loss: 96.8154 - accuracy: 0.4894Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      475/150528000 [..............................] - ETA: 2088:56:45 - loss: 96.516

      521/150528000 [..............................] - ETA: 2088:49:34 - loss: 92.0467 - accuracy: 0.4894Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      525/150528000 [..............................] - ETA: 2088:51:29 - loss: 91.6680 - accuracy: 0.4895Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      527/150528000 [..............................] - ETA: 2088:47:09 - loss: 91.4791 - accuracy: 0.4896Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      531/150528000 [..............................] - ETA: 2088:55:02 - loss: 91.103

      570/150528000 [..............................] - ETA: 2088:58:19 - loss: 87.5062 - accuracy: 0.4877Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      572/150528000 [..............................] - ETA: 2088:57:09 - loss: 87.3241 - accuracy: 0.4895Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      574/150528000 [..............................] - ETA: 2088:56:21 - loss: 87.1447 - accuracy: 0.4895Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      577/150528000 [..............................] - ETA: 2088:57:21 - loss: 86.873

      618/150528000 [..............................] - ETA: 2088:41:37 - loss: 83.2772 - accuracy: 0.4919Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      620/150528000 [..............................] - ETA: 2088:37:50 - loss: 83.1076 - accuracy: 0.4903Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      622/150528000 [..............................] - ETA: 2088:30:03 - loss: 82.9367 - accuracy: 0.4904Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      624/150528000 [..............................] - ETA: 2088:28:56 - loss: 82.765

      670/150528000 [..............................] - ETA: 2087:41:15 - loss: 78.9823 - accuracy: 0.4881Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      672/150528000 [..............................] - ETA: 2087:41:53 - loss: 78.8221 - accuracy: 0.4866Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      674/150528000 [..............................] - ETA: 2087:37:44 - loss: 78.6616 - accuracy: 0.4881Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      676/150528000 [..............................] - ETA: 2087:37:10 - loss: 78.503

      721/150528000 [..............................] - ETA: 2086:57:21 - loss: 75.0343 - accuracy: 0.4882Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      723/150528000 [..............................] - ETA: 2086:53:29 - loss: 74.8847 - accuracy: 0.4882Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      725/150528000 [..............................] - ETA: 2086:52:46 - loss: 74.7361 - accuracy: 0.4869Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      728/150528000 [..............................] - ETA: 2086:48:39 - loss: 74.513

      772/150528000 [..............................] - ETA: 2086:41:30 - loss: 71.3570 - accuracy: 0.4806Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      776/150528000 [..............................] - ETA: 2086:47:32 - loss: 71.0786 - accuracy: 0.4820Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      778/150528000 [..............................] - ETA: 2086:44:08 - loss: 70.9413 - accuracy: 0.4820Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      780/150528000 [..............................] - ETA: 2086:43:47 - loss: 70.805

      824/150528000 [..............................] - ETA: 2086:02:45 - loss: 67.8781 - accuracy: 0.4830Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      826/150528000 [..............................] - ETA: 2086:00:26 - loss: 67.7481 - accuracy: 0.4843Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      828/150528000 [..............................] - ETA: 2085:57:21 - loss: 67.6192 - accuracy: 0.4843Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      830/150528000 [..............................] - ETA: 2085:57:08 - loss: 67.491

Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      876/150528000 [..............................] - ETA: 2085:35:54 - loss: 64.6583 - accuracy: 0.4863Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      878/150528000 [..............................] - ETA: 2085:35:50 - loss: 64.5383 - accuracy: 0.4875Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      880/150528000 [..............................] - ETA: 2085:35:52 - loss: 64.4241 - accuracy: 0.4864Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:

      927/150528000 [..............................] - ETA: 2085:51:11 - loss: 61.7491 - accuracy: 0.4844Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      929/150528000 [..............................] - ETA: 2085:51:06 - loss: 61.6383 - accuracy: 0.4844Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      931/150528000 [..............................] - ETA: 2085:50:49 - loss: 61.5278 - accuracy: 0.4855Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      934/150528000 [..............................] - ETA: 2085:53:26 - loss: 61.361

Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      976/150528000 [..............................] - ETA: 2086:07:02 - loss: 59.1659 - accuracy: 0.4898Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      978/150528000 [..............................] - ETA: 2086:06:55 - loss: 59.0637 - accuracy: 0.4888Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
      980/150528000 [..............................] - ETA: 2086:07:19 - loss: 58.9611 - accuracy: 0.4888Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:

     1025/150528000 [..............................] - ETA: 2086:18:14 - loss: 56.7533 - accuracy: 0.4907Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1027/150528000 [..............................] - ETA: 2086:17:59 - loss: 56.6613 - accuracy: 0.4907Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1031/150528000 [..............................] - ETA: 2086:20:27 - loss: 56.4767 - accuracy: 0.4908Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1034/150528000 [..............................] - ETA: 2086:23:22 - loss: 56.333

     1074/150528000 [..............................] - ETA: 2086:00:54 - loss: 54.5122 - accuracy: 0.4888Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1076/150528000 [..............................] - ETA: 2086:00:05 - loss: 54.4239 - accuracy: 0.4888Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1079/150528000 [..............................] - ETA: 2085:59:55 - loss: 54.2912 - accuracy: 0.4893Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1081/150528000 [..............................] - ETA: 2085:58:21 - loss: 54.202

     1123/150528000 [..............................] - ETA: 2086:03:52 - loss: 52.4123 - accuracy: 0.4915Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1125/150528000 [..............................] - ETA: 2086:03:43 - loss: 52.3304 - accuracy: 0.4916Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1129/150528000 [..............................] - ETA: 2086:05:47 - loss: 52.1695 - accuracy: 0.4898Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1131/150528000 [..............................] - ETA: 2086:05:40 - loss: 52.086

     1172/150528000 [..............................] - ETA: 2086:12:27 - loss: 50.4517 - accuracy: 0.4949Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1175/150528000 [..............................] - ETA: 2086:13:29 - loss: 50.3369 - accuracy: 0.4945Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1177/150528000 [..............................] - ETA: 2086:11:15 - loss: 50.2602 - accuracy: 0.4945Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1179/150528000 [..............................] - ETA: 2086:09:04 - loss: 50.182

     1222/150528000 [..............................] - ETA: 2085:51:38 - loss: 48.5938 - accuracy: 0.4935Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1224/150528000 [..............................] - ETA: 2085:50:45 - loss: 48.5233 - accuracy: 0.4935Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1226/150528000 [..............................] - ETA: 2085:48:41 - loss: 48.4509 - accuracy: 0.4943Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1228/150528000 [..............................] - ETA: 2085:46:35 - loss: 48.379

     1273/150528000 [..............................] - ETA: 2085:30:35 - loss: 46.8223 - accuracy: 0.4965Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1275/150528000 [..............................] - ETA: 2085:28:39 - loss: 46.7556 - accuracy: 0.4965Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1279/150528000 [..............................] - ETA: 2085:31:42 - loss: 46.6263 - accuracy: 0.4949Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1282/150528000 [..............................] - ETA: 2085:32:12 - loss: 46.526

     1322/150528000 [..............................] - ETA: 2085:42:04 - loss: 45.2436 - accuracy: 0.4962Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1325/150528000 [..............................] - ETA: 2085:43:02 - loss: 45.1515 - accuracy: 0.4958Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1327/150528000 [..............................] - ETA: 2085:41:05 - loss: 45.0888 - accuracy: 0.4959Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1329/150528000 [..............................] - ETA: 2085:40:36 - loss: 45.025

     1376/150528000 [..............................] - ETA: 2085:23:17 - loss: 43.6092 - accuracy: 0.4949Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1379/150528000 [..............................] - ETA: 2085:23:15 - loss: 43.5205 - accuracy: 0.4960Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1381/150528000 [..............................] - ETA: 2085:23:10 - loss: 43.4616 - accuracy: 0.4967Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1384/150528000 [..............................] - ETA: 2085:23:20 - loss: 43.374

     1427/150528000 [..............................] - ETA: 2085:04:41 - loss: 42.1643 - accuracy: 0.4968Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1431/150528000 [..............................] - ETA: 2085:07:20 - loss: 42.0552 - accuracy: 0.4962Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1433/150528000 [..............................] - ETA: 2085:06:41 - loss: 42.0003 - accuracy: 0.4962Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1436/150528000 [..............................] - ETA: 2085:06:40 - loss: 41.918

     1477/150528000 [..............................] - ETA: 2085:05:16 - loss: 40.8396 - accuracy: 0.4963Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1479/150528000 [..............................] - ETA: 2085:03:55 - loss: 40.7903 - accuracy: 0.4963Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1481/150528000 [..............................] - ETA: 2085:02:18 - loss: 40.7388 - accuracy: 0.4963Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1484/150528000 [..............................] - ETA: 2085:02:20 - loss: 40.661

Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1528/150528000 [..............................] - ETA: 2084:55:55 - loss: 39.5660 - accuracy: 0.4954Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1530/150528000 [..............................] - ETA: 2084:54:19 - loss: 39.5188 - accuracy: 0.4948Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1532/150528000 [..............................] - ETA: 2084:52:42 - loss: 39.4708 - accuracy: 0.4948Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:

     1578/150528000 [..............................] - ETA: 2084:43:55 - loss: 38.3925 - accuracy: 0.4943Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1580/150528000 [..............................] - ETA: 2084:43:51 - loss: 38.3478 - accuracy: 0.4937Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1584/150528000 [..............................] - ETA: 2084:45:12 - loss: 38.2561 - accuracy: 0.4943Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1586/150528000 [..............................] - ETA: 2084:45:07 - loss: 38.210

     1628/150528000 [..............................] - ETA: 2084:41:34 - loss: 37.2882 - accuracy: 0.4951Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1630/150528000 [..............................] - ETA: 2084:40:04 - loss: 37.2443 - accuracy: 0.4957Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1632/150528000 [..............................] - ETA: 2084:40:05 - loss: 37.2002 - accuracy: 0.4963Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1634/150528000 [..............................] - ETA: 2084:39:59 - loss: 37.161

     1678/150528000 [..............................] - ETA: 2084:40:53 - loss: 36.2523 - accuracy: 0.4964Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1680/150528000 [..............................] - ETA: 2084:40:17 - loss: 36.2120 - accuracy: 0.4964Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1683/150528000 [..............................] - ETA: 2084:41:52 - loss: 36.1576 - accuracy: 0.4961Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1685/150528000 [..............................] - ETA: 2084:41:53 - loss: 36.120

     1729/150528000 [..............................] - ETA: 2084:33:07 - loss: 35.2625 - accuracy: 0.4928Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1731/150528000 [..............................] - ETA: 2084:31:42 - loss: 35.2241 - accuracy: 0.4928Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1733/150528000 [..............................] - ETA: 2084:31:44 - loss: 35.1847 - accuracy: 0.4934Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1735/150528000 [..............................] - ETA: 2084:31:44 - loss: 35.147

     1781/150528000 [..............................] - ETA: 2084:18:37 - loss: 34.2981 - accuracy: 0.4919Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1783/150528000 [..............................] - ETA: 2084:18:38 - loss: 34.2618 - accuracy: 0.4919Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1786/150528000 [..............................] - ETA: 2084:18:52 - loss: 34.2076 - accuracy: 0.4910Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1788/150528000 [..............................] - ETA: 2084:18:53 - loss: 34.171

     1832/150528000 [..............................] - ETA: 2084:23:58 - loss: 33.4059 - accuracy: 0.4918Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1835/150528000 [..............................] - ETA: 2084:25:16 - loss: 33.3539 - accuracy: 0.4921Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1837/150528000 [..............................] - ETA: 2084:25:17 - loss: 33.3197 - accuracy: 0.4921Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1839/150528000 [..............................] - ETA: 2084:25:22 - loss: 33.284

     1879/150528000 [..............................] - ETA: 2084:33:45 - loss: 32.6227 - accuracy: 0.4907Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1881/150528000 [..............................] - ETA: 2084:33:47 - loss: 32.5908 - accuracy: 0.4907Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1883/150528000 [..............................] - ETA: 2084:33:49 - loss: 32.5584 - accuracy: 0.4907Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1886/150528000 [..............................] - ETA: 2084:34:43 - loss: 32.508

Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1929/150528000 [..............................] - ETA: 2084:42:36 - loss: 31.8241 - accuracy: 0.4925Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1931/150528000 [..............................] - ETA: 2084:42:37 - loss: 31.7921 - accuracy: 0.4930Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1935/150528000 [..............................] - ETA: 2084:43:31 - loss: 31.7283 - accuracy: 0.4935Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:

     1979/150528000 [..............................] - ETA: 2084:46:32 - loss: 31.0781 - accuracy: 0.4922Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1981/150528000 [..............................] - ETA: 2084:45:20 - loss: 31.0474 - accuracy: 0.4927Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1983/150528000 [..............................] - ETA: 2084:45:11 - loss: 31.0177 - accuracy: 0.4927Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     1985/150528000 [..............................] - ETA: 2084:43:58 - loss: 30.989

     2028/150528000 [..............................] - ETA: 2084:38:53 - loss: 30.3758 - accuracy: 0.4901Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2031/150528000 [..............................] - ETA: 2084:40:22 - loss: 30.3330 - accuracy: 0.4904Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2033/150528000 [..............................] - ETA: 2084:40:22 - loss: 30.3039 - accuracy: 0.4909Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2035/150528000 [..............................] - ETA: 2084:40:22 - loss: 30.276

     2078/150528000 [..............................] - ETA: 2084:36:41 - loss: 29.6916 - accuracy: 0.4909Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2080/150528000 [..............................] - ETA: 2084:36:45 - loss: 29.6657 - accuracy: 0.4904Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2083/150528000 [..............................] - ETA: 2084:36:44 - loss: 29.6265 - accuracy: 0.4902Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2085/150528000 [..............................] - ETA: 2084:35:36 - loss: 29.599

     2130/150528000 [..............................] - ETA: 2084:36:41 - loss: 29.0055 - accuracy: 0.4887Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2133/150528000 [..............................] - ETA: 2084:37:04 - loss: 28.9663 - accuracy: 0.4890Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2137/150528000 [..............................] - ETA: 2084:37:27 - loss: 28.9137 - accuracy: 0.4895Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2141/150528000 [..............................] - ETA: 2084:39:00 - loss: 28.861

     2177/150528000 [..............................] - ETA: 2084:30:05 - loss: 28.4198 - accuracy: 0.4901Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2180/150528000 [..............................] - ETA: 2084:31:02 - loss: 28.3817 - accuracy: 0.4904Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2183/150528000 [..............................] - ETA: 2084:30:27 - loss: 28.3447 - accuracy: 0.4902Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2185/150528000 [..............................] - ETA: 2084:30:28 - loss: 28.323

Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2229/150528000 [..............................] - ETA: 2084:24:35 - loss: 27.8002 - accuracy: 0.4899Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2231/150528000 [..............................] - ETA: 2084:24:35 - loss: 27.7766 - accuracy: 0.4899Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2233/150528000 [..............................] - ETA: 2084:23:32 - loss: 27.7529 - accuracy: 0.4895Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:

Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2282/150528000 [..............................] - ETA: 2084:24:12 - loss: 27.1921 - accuracy: 0.4921Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2284/150528000 [..............................] - ETA: 2084:23:10 - loss: 27.1738 - accuracy: 0.4917Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2288/150528000 [..............................] - ETA: 2084:25:29 - loss: 27.1338 - accuracy: 0.4908Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:

Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2330/150528000 [..............................] - ETA: 2084:31:21 - loss: 26.6770 - accuracy: 0.4918Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2334/150528000 [..............................] - ETA: 2084:32:33 - loss: 26.6334 - accuracy: 0.4923Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2336/150528000 [..............................] - ETA: 2084:32:39 - loss: 26.6115 - accuracy: 0.4923Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:

     2376/150528000 [..............................] - ETA: 2084:39:17 - loss: 26.1844 - accuracy: 0.4941Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2378/150528000 [..............................] - ETA: 2084:38:45 - loss: 26.1630 - accuracy: 0.4941Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2382/150528000 [..............................] - ETA: 2084:39:50 - loss: 26.1232 - accuracy: 0.4941Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2384/150528000 [..............................] - ETA: 2084:39:39 - loss: 26.101

     2425/150528000 [..............................] - ETA: 2084:45:15 - loss: 25.6851 - accuracy: 0.4961Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2431/150528000 [..............................] - ETA: 2084:46:51 - loss: 25.6244 - accuracy: 0.4965Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2434/150528000 [..............................] - ETA: 2084:47:03 - loss: 25.5959 - accuracy: 0.4963Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2438/150528000 [..............................] - ETA: 2084:47:50 - loss: 25.556

     2474/150528000 [..............................] - ETA: 2084:43:07 - loss: 25.2164 - accuracy: 0.4960Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2476/150528000 [..............................] - ETA: 2084:43:08 - loss: 25.1966 - accuracy: 0.4960Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2478/150528000 [..............................] - ETA: 2084:42:06 - loss: 25.1791 - accuracy: 0.4956Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2480/150528000 [..............................] - ETA: 2084:41:05 - loss: 25.161

Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2528/150528000 [..............................] - ETA: 2084:29:24 - loss: 24.7125 - accuracy: 0.4941Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2530/150528000 [..............................] - ETA: 2084:28:28 - loss: 24.6933 - accuracy: 0.4945Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2532/150528000 [..............................] - ETA: 2084:27:47 - loss: 24.6746 - accuracy: 0.4945Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:

     2578/150528000 [..............................] - ETA: 2084:33:00 - loss: 24.2596 - accuracy: 0.4957Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2580/150528000 [..............................] - ETA: 2084:33:01 - loss: 24.2410 - accuracy: 0.4961Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2582/150528000 [..............................] - ETA: 2084:33:06 - loss: 24.2224 - accuracy: 0.4965Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2584/150528000 [..............................] - ETA: 2084:32:11 - loss: 24.206

     2633/150528000 [..............................] - ETA: 2084:25:24 - loss: 23.7839 - accuracy: 0.4964Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2636/150528000 [..............................] - ETA: 2084:25:29 - loss: 23.7590 - accuracy: 0.4962Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2639/150528000 [..............................] - ETA: 2084:25:31 - loss: 23.7337 - accuracy: 0.4960Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2642/150528000 [..............................] - ETA: 2084:25:32 - loss: 23.707

     2685/150528000 [..............................] - ETA: 2084:17:12 - loss: 23.3512 - accuracy: 0.4980Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2688/150528000 [..............................] - ETA: 2084:17:58 - loss: 23.3282 - accuracy: 0.4974Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2690/150528000 [..............................] - ETA: 2084:17:59 - loss: 23.3123 - accuracy: 0.4974Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2692/150528000 [..............................] - ETA: 2084:17:59 - loss: 23.296

Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2733/150528000 [..............................] - ETA: 2084:14:41 - loss: 22.9694 - accuracy: 0.4976Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2736/150528000 [..............................] - ETA: 2084:14:26 - loss: 22.9444 - accuracy: 0.4982Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2738/150528000 [..............................] - ETA: 2084:13:05 - loss: 22.9278 - accuracy: 0.4985Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:

     2787/150528000 [..............................] - ETA: 2084:36:18 - loss: 22.5461 - accuracy: 0.4998Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2789/150528000 [..............................] - ETA: 2084:37:10 - loss: 22.5312 - accuracy: 0.4998Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2794/150528000 [..............................] - ETA: 2084:40:22 - loss: 22.4917 - accuracy: 0.5004Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2798/150528000 [..............................] - ETA: 2084:42:11 - loss: 22.463

     2824/150528000 [..............................] - ETA: 2084:57:17 - loss: 22.2654 - accuracy: 0.5000Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2831/150528000 [..............................] - ETA: 2085:00:44 - loss: 22.2137 - accuracy: 0.4998Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2834/150528000 [..............................] - ETA: 2085:02:33 - loss: 22.1905 - accuracy: 0.5004Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2840/150528000 [..............................] - ETA: 2085:04:58 - loss: 22.146

     2873/150528000 [..............................] - ETA: 2085:22:31 - loss: 21.9066 - accuracy: 0.4998Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2898/150528000 [..............................] - ETA: 2085:45:38 - loss: 21.7294 - accuracy: 0.4986Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2901/150528000 [..............................] - ETA: 2085:47:17 - loss: 21.7080 - accuracy: 0.4988Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2903/150528000 [..............................] - ETA: 2085:48:08 - loss: 21.694

     2912/150528000 [..............................] - ETA: 2085:51:53 - loss: 21.6312 - accuracy: 0.4983Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2915/150528000 [..............................] - ETA: 2085:52:40 - loss: 21.6108 - accuracy: 0.4981Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2918/150528000 [..............................] - ETA: 2085:54:20 - loss: 21.5906 - accuracy: 0.4983Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2931/150528000 [..............................] - ETA: 2086:01:26 - loss: 21.502

     2959/150528000 [..............................] - ETA: 2086:14:24 - loss: 21.3092 - accuracy: 0.4975Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2961/150528000 [..............................] - ETA: 2086:15:12 - loss: 21.2967 - accuracy: 0.4971Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2964/150528000 [..............................] - ETA: 2086:16:31 - loss: 21.2760 - accuracy: 0.4973Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     2969/150528000 [..............................] - ETA: 2086:18:28 - loss: 21.242

     3002/150528000 [..............................] - ETA: 2086:35:52 - loss: 21.0230 - accuracy: 0.4963Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     3008/150528000 [..............................] - ETA: 2086:38:48 - loss: 20.9826 - accuracy: 0.4967Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     3013/150528000 [..............................] - ETA: 2086:41:32 - loss: 20.9498 - accuracy: 0.4968Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     3015/150528000 [..............................] - ETA: 2086:42:00 - loss: 20.936

     3056/150528000 [..............................] - ETA: 2087:03:07 - loss: 20.6733 - accuracy: 0.4977Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     3062/150528000 [..............................] - ETA: 2087:06:29 - loss: 20.6365 - accuracy: 0.4977Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     3072/150528000 [..............................] - ETA: 2087:11:40 - loss: 20.5752 - accuracy: 0.4980Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     3076/150528000 [..............................] - ETA: 2087:13:33 - loss: 20.552

     3095/150528000 [..............................] - ETA: 2087:24:56 - loss: 20.4354 - accuracy: 0.4966Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     3098/150528000 [..............................] - ETA: 2087:26:25 - loss: 20.4172 - accuracy: 0.4961Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     3106/150528000 [..............................] - ETA: 2087:29:47 - loss: 20.3673 - accuracy: 0.4961Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     3113/150528000 [..............................] - ETA: 2087:32:54 - loss: 20.325

     3139/150528000 [..............................] - ETA: 2087:32:15 - loss: 20.1654 - accuracy: 0.4967Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     3141/150528000 [..............................] - ETA: 2087:31:41 - loss: 20.1526 - accuracy: 0.4970Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     3143/150528000 [..............................] - ETA: 2087:30:49 - loss: 20.1400 - accuracy: 0.4973Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     3146/150528000 [..............................] - ETA: 2087:30:48 - loss: 20.122

     3189/150528000 [..............................] - ETA: 2087:22:03 - loss: 19.8676 - accuracy: 0.4964Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     3191/150528000 [..............................] - ETA: 2087:21:13 - loss: 19.8553 - accuracy: 0.4967Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     3193/150528000 [..............................] - ETA: 2087:20:21 - loss: 19.8442 - accuracy: 0.4964Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     3196/150528000 [..............................] - ETA: 2087:19:50 - loss: 19.826

     3241/150528000 [..............................] - ETA: 2087:14:06 - loss: 19.5706 - accuracy: 0.4955Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     3243/150528000 [..............................] - ETA: 2087:13:16 - loss: 19.5595 - accuracy: 0.4955Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     3246/150528000 [..............................] - ETA: 2087:13:19 - loss: 19.5425 - accuracy: 0.4957Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     3249/150528000 [..............................] - ETA: 2087:12:55 - loss: 19.526

     3292/150528000 [..............................] - ETA: 2087:04:07 - loss: 19.2823 - accuracy: 0.4976Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     3295/150528000 [..............................] - ETA: 2087:03:29 - loss: 19.2656 - accuracy: 0.4977Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     3297/150528000 [..............................] - ETA: 2087:02:07 - loss: 19.2541 - accuracy: 0.4980Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     3299/150528000 [..............................] - ETA: 2087:01:56 - loss: 19.242

Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     3344/150528000 [..............................] - ETA: 2086:55:01 - loss: 19.0026 - accuracy: 0.4991Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     3346/150528000 [..............................] - ETA: 2086:54:22 - loss: 18.9914 - accuracy: 0.4994Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
     3348/150528000 [..............................] - ETA: 2086:53:02 - loss: 18.9814 - accuracy: 0.4994Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op __inference_train_function_2796 in device /job:localhost/replica:0/task:

In [ ]:
%tensorboard --logdir logs/vgg_minibatch

In [ ]:
print('train loss:', history.history['loss'][-1])
print('train accuracy:', history.history['accuracy'][-1])

print('dev loss:', history.history['val_loss'][-1])
print('dev accuracy:', history.history['val_accuracy'][-1])

fig, axs = plt.subplots(1,2,figsize=(15,5))

axs[0].plot(range(1,len(history.history['accuracy'])+1), history.history['accuracy'])
axs[0].plot(range(1,len(history.history['val_accuracy'])+1),history.history['val_accuracy'])
axs[0].set_title('Model Accuracy')
axs[0].set_ylabel('Accuracy')
axs[0].set_xlabel('Epoch')
axs[0].legend(['train', 'val'], loc='best')

axs[1].plot(range(1,len(history.history['loss'])+1),history.history['loss'])
axs[1].plot(range(1,len(history.history['val_loss'])+1),history.history['val_loss'])
axs[1].set_title('Model Loss')
axs[1].set_ylabel('Loss')
axs[1].set_xlabel('Epoch')
axs[1].legend(['train', 'val'], loc='best')

plt.show()

In [ ]:
# test_loss, test_acc = model.evaluate(x_test, y_test)

In [ ]:
# print('test loss:', test_loss)
# print('test accuracy:', test_acc)

In [ ]:
predictions = model.predict(x_test)

In [ ]:
print(predictions)

y_pred = []

for i in predictions:
    if i[0] < i[1]:
        y_pred.append(1)
    else:
        y_pred.append(0)

In [ ]:
from sklearn.metrics import confusion_matrix

confusion_mtx = confusion_matrix(y_test, y_pred)

In [ ]:
import seaborn as sns

f, ax = plt.subplots(figsize=(8, 8))
sns.heatmap(confusion_mtx, annot=True, linewidths=0.01, cmap="Greens",linecolor="gray", fmt='.1f', ax=ax)
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix")
plt.show()

In [ ]:
from sklearn.metrics import classification_report

# Generate a classification report
report = classification_report(y_test, y_pred, target_names=['cat', 'dog'])

In [ ]:
print(report)

In [ ]:
print('Precision:- Accuracy of positive predictions.')
print('Precision = TP/(TP + FP)')
print('Recall:- Fraction of positives that were correctly identified.')
print('Recall = TP/(TP+FN)')
print('F1 score')
print('F1 Score = 2*(Recall * Precision) / (Recall + Precision)')
print('Accuracy : (TP+TN) / all')
print('macro avg = (normal+abnormal)/2 * precision or recall or f1 score')
print('weighted avg = normal/(normal+abnormal) * precision or recall or f1 score')