In [1]:
import numpy as np

a = np.random.randn(5)

In [2]:
print(a)

[-0.5257799   1.1235285   0.22989434  1.59368884 -0.17150011]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[-0.5257799   1.1235285   0.22989434  1.59368884 -0.17150011]


In [5]:
print(np.dot(a, a.T))

4.160868581202159


In [6]:
a = np.random.randn(5,1)

In [7]:
print(a)

[[-1.12883939]
 [ 0.82497907]
 [ 0.41493699]
 [ 0.50554901]
 [ 0.34110332]]


In [8]:
print(a.T)

[[-1.12883939  0.82497907  0.41493699  0.50554901  0.34110332]]


In [9]:
print(np.dot(a, a.T))

[[ 1.27427836 -0.93126887 -0.46839721 -0.57068364 -0.38505086]
 [-0.93126887  0.68059047  0.34231433  0.41706736  0.2814031 ]
 [-0.46839721  0.34231433  0.1721727   0.20977098  0.14153638]
 [-0.57068364  0.41706736  0.20977098  0.2555798   0.17244445]
 [-0.38505086  0.2814031   0.14153638  0.17244445  0.11635148]]
